version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres_db
    environment:
      # Zmienne przekazywane z pliku .env generowanego przez GitHub Actions
      POSTGRES_DB: app
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      # Healthcheck też musi używać zmiennej dla nazwy użytkownika
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d app"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_backend
    env_file:
      - .env # Zasysa SPRING_DATASOURCE_URL, USERNAME i PASSWORD
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=eu-central-1
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      # NOWE: Mapowanie wolumenu dla plików
      - backend_uploads:/app/uploads

  frontend:
    build:
      context: ./business-frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  backend_uploads:

networks:
  app-network:
    driver: bridge