spring.application.name=backend

# Import secret datasource and AWS Cognito properties
# spring.datasource.url
# spring.datasource.username
# spring.datasource.password
# aws.cognito.user-pool-id
# aws.cognito.client-id
# aws.cognito.region
# aws.access-key-id
# aws.secret-access-key
spring.config.import=optional:classpath:application.secret[.properties]

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Upload and Static Resource Configuration
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# AWS & Cognito Default Configuration
aws.cognito.region=${AWS_REGION:eu-central-1}
