name: App Deploy

on:
  workflow_call:

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy na serwer EC2 przez SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Jeśli folderu nie ma, klonuje repozytorium używając tokena GH_PAT
            if [ ! -d "hackathon-aws-terraform-test" ]; then
              git clone https://${{ secrets.GH_PAT }}@github.com/garnaalpak/hackathon-aws-terraform-test.git
            fi
            
            cd hackathon-aws-terraform-test
            
            # Pobiera najnowsze zmiany
            git pull origin main
            
            # Tworzenie pliku .env z sekretów GitHuba
            echo "SPRING_DATASOURCE_URL=${{ secrets.DB_URL }}" > .env
            echo "SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "SPRING_DATASOURCE_URL=${{ secrets.DB_URL }}" > .env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "AWS_REGION=eu-central-1" >> .env
            echo "COGNITO_USER_POOL_ID=${{ secrets.COGNITO_USER_POOL_ID }}" >> .env
            echo "COGNITO_CLIENT_ID=${{ secrets.COGNITO_CLIENT_ID }}" >> .env
            echo "AWS_COGNITO_REGION=eu-central-1" >> .env
            
            # Stawia kontenery
            docker compose up -d --build