name: Frontend Validate

on:
  workflow_call: # Pozwala wywołać ten plik z innego workflow

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: business-frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./business-frontend
        run: npm ci

      - name: Build
        working-directory: ./business-frontend
        run: npm run build